global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - 127.0.0.1:9090
  - job_name: "node-exporter"
    static_configs:
      - targets:
        - id1.fazzhost.com:9100
        - id2.fazzhost.com:9100
        - id3.fazzhost.com:9100
  - job_name: 'snmp-exporter'
    static_configs:
      - targets:
        - sg1.fazzhost.com
        - sg2.fazzhost.com
        - sg3.fazzhost.com
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116
